-- Patch tambahan modul rekam medis rinci Klinik Pintar
-- Aman dijalankan berulang kali karena menggunakan CREATE TABLE IF NOT EXISTS

CREATE TABLE IF NOT EXISTS patient_medical_profiles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    patient_id INT NOT NULL UNIQUE,
    blood_type VARCHAR(10) DEFAULT NULL,
    allergy_notes TEXT DEFAULT NULL,
    chronic_conditions TEXT DEFAULT NULL,
    past_medical_history TEXT DEFAULT NULL,
    surgery_history TEXT DEFAULT NULL,
    family_history TEXT DEFAULT NULL,
    medication_history TEXT DEFAULT NULL,
    vaccination_history TEXT DEFAULT NULL,
    lifestyle_notes TEXT DEFAULT NULL,
    pregnancy_notes TEXT DEFAULT NULL,
    alert_notes TEXT DEFAULT NULL,
    special_condition_notes TEXT DEFAULT NULL,
    created_at DATETIME DEFAULT NULL,
    updated_at DATETIME DEFAULT NULL,
    CONSTRAINT fk_patient_medical_profiles_patient FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS medical_records (
    id INT AUTO_INCREMENT PRIMARY KEY,
    visit_id INT NOT NULL UNIQUE,
    patient_id INT NOT NULL,
    branch_id INT NOT NULL,
    clinic_id INT DEFAULT NULL,
    doctor_user_id INT DEFAULT NULL,
    anamnesis TEXT DEFAULT NULL,
    complaint_history TEXT DEFAULT NULL,
    physical_exam TEXT DEFAULT NULL,
    subjective_notes TEXT DEFAULT NULL,
    objective_notes TEXT DEFAULT NULL,
    assessment_notes TEXT DEFAULT NULL,
    plan_notes TEXT DEFAULT NULL,
    diagnosis_secondary TEXT DEFAULT NULL,
    procedure_notes TEXT DEFAULT NULL,
    lab_notes TEXT DEFAULT NULL,
    radiology_notes TEXT DEFAULT NULL,
    allergy_confirmation TEXT DEFAULT NULL,
    condition_flags TEXT DEFAULT NULL,
    control_plan TEXT DEFAULT NULL,
    next_control_date DATE DEFAULT NULL,
    referral_notes TEXT DEFAULT NULL,
    special_condition TINYINT(1) NOT NULL DEFAULT 0,
    special_condition_details TEXT DEFAULT NULL,
    created_at DATETIME DEFAULT NULL,
    updated_at DATETIME DEFAULT NULL,
    CONSTRAINT fk_medical_records_visit FOREIGN KEY (visit_id) REFERENCES visits(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_medical_records_patient FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_medical_records_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_medical_records_clinic FOREIGN KEY (clinic_id) REFERENCES clinics(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_medical_records_doctor FOREIGN KEY (doctor_user_id) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS patient_monitoring_plans (
    id INT AUTO_INCREMENT PRIMARY KEY,
    patient_id INT NOT NULL,
    branch_id INT NOT NULL,
    clinic_id INT DEFAULT NULL,
    created_from_visit_id INT DEFAULT NULL,
    doctor_user_id INT DEFAULT NULL,
    program_name VARCHAR(150) NOT NULL,
    condition_name VARCHAR(150) DEFAULT NULL,
    frequency_label VARCHAR(100) DEFAULT NULL,
    start_date DATE NOT NULL,
    end_date DATE DEFAULT NULL,
    next_control_date DATE DEFAULT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    notes TEXT DEFAULT NULL,
    created_at DATETIME DEFAULT NULL,
    updated_at DATETIME DEFAULT NULL,
    CONSTRAINT fk_patient_monitoring_patient FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_patient_monitoring_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_patient_monitoring_clinic FOREIGN KEY (clinic_id) REFERENCES clinics(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_patient_monitoring_visit FOREIGN KEY (created_from_visit_id) REFERENCES visits(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_patient_monitoring_doctor FOREIGN KEY (doctor_user_id) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
