ALTER TABLE users ADD COLUMN phone VARCHAR(30) DEFAULT NULL AFTER email;
ALTER TABLE users ADD COLUMN gender VARCHAR(20) DEFAULT NULL AFTER phone;
ALTER TABLE users ADD COLUMN address TEXT DEFAULT NULL AFTER gender;
ALTER TABLE users ADD COLUMN bio TEXT DEFAULT NULL AFTER address;
ALTER TABLE users ADD COLUMN photo_path VARCHAR(255) DEFAULT NULL AFTER bio;
